server:
  port: 8090

  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

spring:
  #profiles:
    #active: deploy


  application:
    name: SWITCH-PAYCO
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/payco
    username: root
    password: Avatar1@


logging:
  file:
    name: payco-logs.log